In [1]:
from pyscf.lib import dot
import numpy as np

print( np.array([[[1,1],[2,2]], [[3,3], [4,4]], [[5,5], [6,6]]]).reshape(3,-1))

[[1 1 2 2]
 [3 3 4 4]
 [5 5 6 6]]


In [8]:
from pyscf import gto
from pyscf.scf import hf
from pyscf.mcscf.mc1step import CASSCF

mol = gto.M(atom='H 0 0 0; H 0.740852 0 0', basis='cc-pvdz')
mf = hf.RHF(mol); mf.kernel()

cas = CASSCF(mf, 2, 2) # 
cas.kernel()

print(cas.ci) # 2 * 2
print(cas.mo_coeff.shape)   # (10, 10)

print(cas.get_h2eff().shape)

converged SCF energy = -1.1287094895614
Call direct_spin1!
CASSCF energy = -1.1469082901018
CASCI E = -1.1469082901018  E(CI) = -1.86119023969497  S^2 = 0.0000000
[[ 9.94052033e-01  1.18008351e-13]
 [ 1.18008633e-13 -1.08906175e-01]]
(10, 10)
(3, 3)
